version: '3'

services:

  core:
    build: ./core
    ports:
      - "1234:1234"
    volumes:
    - ./mnt/templates:/app/templates
    - ./mnt/flag:/flag

  vec:
    build: ./vec
    ports:
      - "3000:3000"
    volumes:
      - ./templates:/app/templates

  registry:
    image: registry:2
    ports:
      -5000:5000