[profile.default]
src="src/"
out = "out"
libs = ["lib"]

remappings=["@openzeppelin/contracts/=src/openzeppelin-contracts/",]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fs_permissions = [{ access = "read", path = "./"}]

[profile.core]
src="src/core/"
solc="0.8.20"

[profile.uniswap]
src="src/uniswap-v2/"
solc="0.5.16"
test="src/uniswap-v2/test"
